// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: api/proto/v1/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FalconQueueService_SubmitJob_FullMethodName      = "/v1.FalconQueueService/SubmitJob"
	FalconQueueService_RegisterWorker_FullMethodName = "/v1.FalconQueueService/RegisterWorker"
	FalconQueueService_SendHeartbeat_FullMethodName  = "/v1.FalconQueueService/SendHeartbeat"
	FalconQueueService_PollJobs_FullMethodName       = "/v1.FalconQueueService/PollJobs"
	FalconQueueService_AcknowledgeJob_FullMethodName = "/v1.FalconQueueService/AcknowledgeJob"
)

// FalconQueueServiceClient is the client API for FalconQueueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FalconQueueService defines the RPC methods for the distributed queue system.
type FalconQueueServiceClient interface {
	// Job Management
	SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error)
	// Worker Coordination
	RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error)
	SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	PollJobs(ctx context.Context, in *PollJobsRequest, opts ...grpc.CallOption) (*PollJobsResponse, error)
	AcknowledgeJob(ctx context.Context, in *AcknowledgeJobRequest, opts ...grpc.CallOption) (*AcknowledgeJobResponse, error)
}

type falconQueueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFalconQueueServiceClient(cc grpc.ClientConnInterface) FalconQueueServiceClient {
	return &falconQueueServiceClient{cc}
}

func (c *falconQueueServiceClient) SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitJobResponse)
	err := c.cc.Invoke(ctx, FalconQueueService_SubmitJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *falconQueueServiceClient) RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterWorkerResponse)
	err := c.cc.Invoke(ctx, FalconQueueService_RegisterWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *falconQueueServiceClient) SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, FalconQueueService_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *falconQueueServiceClient) PollJobs(ctx context.Context, in *PollJobsRequest, opts ...grpc.CallOption) (*PollJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollJobsResponse)
	err := c.cc.Invoke(ctx, FalconQueueService_PollJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *falconQueueServiceClient) AcknowledgeJob(ctx context.Context, in *AcknowledgeJobRequest, opts ...grpc.CallOption) (*AcknowledgeJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcknowledgeJobResponse)
	err := c.cc.Invoke(ctx, FalconQueueService_AcknowledgeJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FalconQueueServiceServer is the server API for FalconQueueService service.
// All implementations must embed UnimplementedFalconQueueServiceServer
// for forward compatibility.
//
// FalconQueueService defines the RPC methods for the distributed queue system.
type FalconQueueServiceServer interface {
	// Job Management
	SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error)
	// Worker Coordination
	RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error)
	SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	PollJobs(context.Context, *PollJobsRequest) (*PollJobsResponse, error)
	AcknowledgeJob(context.Context, *AcknowledgeJobRequest) (*AcknowledgeJobResponse, error)
	mustEmbedUnimplementedFalconQueueServiceServer()
}

// UnimplementedFalconQueueServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFalconQueueServiceServer struct{}

func (UnimplementedFalconQueueServiceServer) SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitJob not implemented")
}
func (UnimplementedFalconQueueServiceServer) RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (UnimplementedFalconQueueServiceServer) SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedFalconQueueServiceServer) PollJobs(context.Context, *PollJobsRequest) (*PollJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PollJobs not implemented")
}
func (UnimplementedFalconQueueServiceServer) AcknowledgeJob(context.Context, *AcknowledgeJobRequest) (*AcknowledgeJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcknowledgeJob not implemented")
}
func (UnimplementedFalconQueueServiceServer) mustEmbedUnimplementedFalconQueueServiceServer() {}
func (UnimplementedFalconQueueServiceServer) testEmbeddedByValue()                            {}

// UnsafeFalconQueueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FalconQueueServiceServer will
// result in compilation errors.
type UnsafeFalconQueueServiceServer interface {
	mustEmbedUnimplementedFalconQueueServiceServer()
}

func RegisterFalconQueueServiceServer(s grpc.ServiceRegistrar, srv FalconQueueServiceServer) {
	// If the following call panics, it indicates UnimplementedFalconQueueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FalconQueueService_ServiceDesc, srv)
}

func _FalconQueueService_SubmitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FalconQueueServiceServer).SubmitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FalconQueueService_SubmitJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FalconQueueServiceServer).SubmitJob(ctx, req.(*SubmitJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FalconQueueService_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FalconQueueServiceServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FalconQueueService_RegisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FalconQueueServiceServer).RegisterWorker(ctx, req.(*RegisterWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FalconQueueService_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FalconQueueServiceServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FalconQueueService_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FalconQueueServiceServer).SendHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FalconQueueService_PollJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FalconQueueServiceServer).PollJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FalconQueueService_PollJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FalconQueueServiceServer).PollJobs(ctx, req.(*PollJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FalconQueueService_AcknowledgeJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FalconQueueServiceServer).AcknowledgeJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FalconQueueService_AcknowledgeJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FalconQueueServiceServer).AcknowledgeJob(ctx, req.(*AcknowledgeJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FalconQueueService_ServiceDesc is the grpc.ServiceDesc for FalconQueueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FalconQueueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.FalconQueueService",
	HandlerType: (*FalconQueueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitJob",
			Handler:    _FalconQueueService_SubmitJob_Handler,
		},
		{
			MethodName: "RegisterWorker",
			Handler:    _FalconQueueService_RegisterWorker_Handler,
		},
		{
			MethodName: "SendHeartbeat",
			Handler:    _FalconQueueService_SendHeartbeat_Handler,
		},
		{
			MethodName: "PollJobs",
			Handler:    _FalconQueueService_PollJobs_Handler,
		},
		{
			MethodName: "AcknowledgeJob",
			Handler:    _FalconQueueService_AcknowledgeJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/service.proto",
}
